name: DeployStaging
on:
  push:
    branches: [ nextjs ]
jobs:
  Deploy_to_GAE:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: npm run install
      - run: npm run build
      #      - run: npm run test

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{secrets.PROJECT_ID_STG}}
          service_account_key: ${{secrets.GCP_SA_KEY_STG}}

      - name: Deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.PROJECT_ID_STG }}
          credentials: ${{ secrets.GCP_SA_KEY_STG}}
          promote: true
          version: v1
